name: prod deploy
on: 
  push:
    branches:
      - master
  repository_dispatch:
    types: rebuildprod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 30m
          command_timeout: 60m  
          script: |
            cd /home/git/Delivly-API
            pm2 delete api
            git stash
            git pull origin master
            npm i
            pm2 start npm --name api -- start
